version: '3.8'

services:
  app:
    image: registry.gitlab.com/gsc/gsc-countdown-app
    container_name: app
    restart: on-failure
    env_file: .env
    depends_on:
      - pg
    ports:
      - 3000:3000
    environment:
      - POSTGRES_URL=postgresql://postgres:postgres@pg:5432/cd

  pg:
    image: postgres:15.1
    container_name: pg
    restart: on-failure
    ports:
      - 5445:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  db:
    driver: local
